version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
  
clone_depth: 1

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore  

after_build:
  - cmd: teamcity-plugin\Build\build-metarunner.cmd
  - cmd: 7z a OctopusPuppet.Cmd.zip %APPVEYOR_BUILD_FOLDER%\src\OctopusPuppet.Cmd\bin\Release\*.*
  - cmd: 7z a OctopusPuppet.Gui.zip %APPVEYOR_BUILD_FOLDER%\src\OctopusPuppet.Gui\bin\Release\*.*

artifacts:
  - path: OctopusPuppet.Cmd.zip
    name: OctopusPuppet.Cmd
    type: zip

  - path: OctopusPuppet.Gui.zip
    name: OctopusPuppet.Gui
    type: zip

  - path: octopuspuppet-metarunner.zip
    name: OctopusPuppet.Teamcity
    type: zip    

configuration: Release

build:
  verbosity: minimal

test:
  assemblies: '*.Tests.dll'  

image: Visual Studio 2015

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%