version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
  
clone_depth: 1

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore  

configuration: Release

build:
  verbosity: minimal
    
on_finish:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker
  - ps: |
      If ($env:APPVEYOR_REPO_BRANCH -eq 'ci-debug') 
      { 
        $blockRdp = $true
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }